# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  biot_data_production:
  static_volume:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - biot_data_production:/var/lib/postgresql/data

  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: practic73/biot_backend
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static_volume:/backend_static

    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  # Имя третьего контейнера. Это контейнер с фронтендом
  # frontend:
  #   env_file: .env
  #   build: ./frontend/
  # Добавляем новый контейнер: gateway.
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    image: practic73/biot_gateway
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static_volume:/staticfiles/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    ports:
      - 8000:80 