# Generated by Django 4.2.8 on 2024-03-28 04:54

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', validators=[users.validators.real_age], verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
