# Generated by Django 4.2.8 on 2024-03-28 05:41

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, default='1940-01-01', validators=[users.validators.real_age], verbose_name='Дата рождения'),
        ),
    ]
