# Generated by Django 4.2.8 on 2024-03-28 05:42

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, default=None, validators=[users.validators.real_age], verbose_name='Дата рождения'),
        ),
    ]
