# Generated by Django 4.2.8 on 2024-08-08 07:59

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('anonim', 'аноним'), ('user', 'пользователь'), ('moderator', 'модератор'), ('admin', 'администратор'), ('teacher', 'преподователь')], default='anonim', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[users.validators.real_age], verbose_name='Дата рождения'),
        ),
    ]
