# Generated by Django 4.2.8 on 2024-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_role_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('anonim', 'Аноним'), ('user', 'Пользователь')], default='anonim', max_length=20, verbose_name='Роль'),
        ),
    ]
