# Generated by Django 4.2.8 on 2024-03-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReestrOt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reestr_number', models.CharField(help_text='Номер в реестре', max_length=25, unique=True, verbose_name='Номер реестра')),
                ('reestr_date', models.CharField(help_text='Дата внесения в реестр', max_length=15, verbose_name='Дата реестра')),
                ('reestr_id_packet', models.CharField(help_text='ID пакета в реестре', max_length=15, verbose_name='ID пакета')),
                ('is_sistem', models.BooleanField(blank=True, default=False, help_text='Сдача экзамена в системе ЕИСОТ', verbose_name='В системе')),
                ('prot_number', models.CharField(help_text='Номер протокола', max_length=15, verbose_name='Номер протокола')),
                ('prot_date', models.CharField(blank=True, help_text='Дата проверки знаний', max_length=15, verbose_name='Дата протокола')),
                ('program', models.TextField(help_text='Программа обучения', max_length=256, verbose_name='Программа')),
                ('result', models.CharField(help_text='Результат проверки знаний', max_length=25, verbose_name='Результат')),
                ('employer', models.CharField(blank=True, help_text='Наименование работодателя', max_length=100, verbose_name='Работодатель')),
                ('employer_inn', models.CharField(help_text='ИНН работодателя', max_length=25, verbose_name='ИНН работодателя')),
                ('position_at_work', models.CharField(blank=True, help_text='Должность', max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'реестр',
                'verbose_name_plural': 'Выписка из реестра ЕИСОТ',
            },
        ),
    ]
