# Generated by Django 4.2.8 on 2024-08-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=350, unique=True, verbose_name='Название'),
        ),
    ]
