# Generated by Django 4.2.8 on 2024-08-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_number', models.CharField(help_text='Номер группы', max_length=25, unique=True, verbose_name='Номер группы')),
                ('program_training', models.TextField(help_text='Программа обучения', max_length=500, verbose_name='Программа обучения')),
                ('start_date', models.DateField(null=True, verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'Группы обучения',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='UID обучающегося', max_length=30, verbose_name='UID')),
                ('status', models.CharField(choices=[('candidate', 'кандидат'), ('student', 'студент'), ('master', 'выпускник')], default='candidate', help_text='Статус обучающегося', max_length=15, verbose_name='Статус')),
                ('start_date', models.CharField(blank=True, help_text='Дата начала обучения', max_length=15, verbose_name='Дата начала обучения')),
                ('end_date', models.CharField(blank=True, help_text='Дата окончания обучения', max_length=15, verbose_name='Дата окончания обучения')),
                ('groups', models.ManyToManyField(related_name='groups', to='lk.group', verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'обучающийся',
                'verbose_name_plural': 'Обучающиеся',
            },
        ),
    ]
