# Generated by Django 4.2.8 on 2024-08-12 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(help_text='Номер группы', max_length=25, unique=True, verbose_name='Номер группы')),
                ('program_training', models.TextField(help_text='Программа обучения', max_length=500, verbose_name='Программа обучения')),
                ('start_date', models.DateField(null=True, verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'Группы обучения',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='UID обучающегося', max_length=50, verbose_name='UID')),
                ('previous_groups', models.CharField(blank=True, help_text='Предыдущие группы', max_length=30, verbose_name='Предыдущие группы')),
                ('status', models.CharField(choices=[('candidate', 'Кандидат'), ('student', 'Обучающийся'), ('master', 'Выпускник')], default='candidate', help_text='Статус обучающегося', max_length=15, verbose_name='Статус')),
                ('start_date_person', models.DateField(null=True, verbose_name='Дата начала обучения')),
                ('end_date_person', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='lk.group', verbose_name='Текущая группа')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='обучающийся', to=settings.AUTH_USER_MODEL, verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'обучающийся',
                'verbose_name_plural': 'Обучающиеся',
            },
        ),
    ]
